tap "homebrew/bundle"
tap "homebrew/core"
tap "shivammathur/php"

# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Dependency Manager for PHP
brew "composer"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# More intuitive version of du in rust
brew "dust"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Open-source GitLab command-line tool
brew "glab"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Utility for directing compilation
brew "make"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Open source relational database management system
brew "mysql"
# Free (GNU) replacement for the Pico text editor
brew "nano"
# General-purpose scripting language
brew "php"
# Very fast implementation of tldr in Rust
brew "tealdeer"
# Text interface for Git repositories
brew "tig"
# Program that allows you to count code, quickly
brew "tokei"
# Display directories as trees (with optional color/HTML output)
brew "tree"
brew "volta"
# Internet file retriever
brew "wget"
# UNIX shell (command interpreter)
brew "zsh"
# Additional completion definitions for zsh
brew "zsh-completions"
# General-purpose scripting language
brew "shivammathur/php/php@7.4"
