#!/usr/bin/env sh

git_dir="$(git rev-parse --show-toplevel)/.git"

if [ -d "$git_dir" ]; then
  id="$(GH_FORCE_TTY=100% gh pr list | fzf --height ~40% --ansi --preview 'GH_FORCE_TTY=100% gh pr view {1}' --header-lines 3 --pointer="" | awk '{print $1}')";
  [ -n "$id" ] && gh pr checkout "$id"
else
  exit 1
fi
