#!/usr/bin/env sh

if [ -d "./.git" ]; then
  headline="Current branch: $(git branch --show-current)"
  git branch |
  grep --invert-match '\*' |
  cut -c 3- |
  fzf --height 40% --header="$headline" --preview="git log {} --" |
  xargs git switch
else
  echo "Error: there's no .git dir"
  exit 1
fi
