#!/usr/bin/env sh

if [ -d "./.git" ]; then
  headline="Current branch: $(git branch --show-current)"

  git branch --sort=-committerdate |
  grep --invert-match '\*' |
  grep --invert-match --extended-regexp "\smaster$" |
  cut -c 3- |
  fzf --height 40% --header="$headline" --multi --preview="git log {1} --color=always" --pointer="" |
  xargs git branch --delete --force
else
  echo "Error: there's no .git dir"
  exit 1
fi
