#!/usr/bin/env sh

git_dir="$(git rev-parse --show-toplevel)/.git"

if [ -d "$git_dir" ]; then
  headline="Current branch: $(git branch --show-current)"

  git branch --sort=-committerdate |
  grep --invert-match '\*' |
  cut -c 3- |
  fzf --height ~40% --header="$headline" --preview="git log {1} --color=always" --pointer="" |
  xargs git switch
else
  exit 1
fi
