#!/usr/bin/env sh

git_dir="$(git rev-parse --show-toplevel)/.git"

if [ -d "$git_dir" ]; then
  id="$(glab mr list | fzf --height ~40% --preview 'glab mr view {1}' --header-lines 2 --pointer="" | cut -f1)";
  [ -n "$id" ] && glab mr checkout "$id"
else
  exit 1
fi
